Optionally export the AWS_SESSION_TOKEN
naftulikay/aws-env pull request #14
Opened 2019-04-02 14:24 UTC by blacs30

When using onelogin-aws-cli the AWS_SESSION_TOKEN is written into the ~/.aws/credentials file for a profile.
That token has to be exported as well to be able to use e.g. the aws-cli.

This PR adds the function to also export the AWS_SESSION_TOKEN if present.

2019-04-04 20:13 UTC, naftulikay requested changes
Excellent work, thank you for your contribution! I think if you remove the reference to your hardcoded GnuPG binary path and squash, should be ready for merge.

2019-04-04 20:13 UTC, naftulikay commented on src/awsenv/tests.py
> +        self.assertIn(detected_path, ['/usr/bin/gpg2', '/usr/bin/gpg', '/usr/local/MacGPG2/bin/gpg2'])
this needs to be removed

2019-04-08 18:18 UTC, blacs30 commented on src/awsenv/tests.py
> +        self.assertIn(detected_path, ['/usr/bin/gpg2', '/usr/bin/gpg', '/usr/local/MacGPG2/bin/gpg2'])
I've removed the hard coded path.

2019-04-08 18:19 UTC, naftulikay approved these changes
LGTM :+1: Please squash and I'll merge.

2019-04-08 18:36 UTC, blacs30 commented
@naftulikay I've squashed my commits. Hope it looks good (honestly it was the first time I squashed something.. good to have learned little bit about that.)

2019-04-08 18:37 UTC, merged

2019-04-08 18:37 UTC, naftulikay commented
Merged, thank you so much for your contribution!

2019-08-14 20:36 UTC, naftulikay commented
Released in [v1.2.0](https://github.com/naftulikay/aws-env/releases/tag/v1.2.0).